CREATE TABLE teacher(
	id INT AUTO_INCREMENT PRIMARY KEY,
	fullname VARCHAR(35) NOT NULL,
	gender VARCHAR(3) NOT NULL,
	dateOfBirth DATETIME NOT NULL,
	address VARCHAR(100) NOT NULL,
	phone VARCHAR(10)
);